# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `docile` gem.
# Please instead update this file by running `bin/tapioca gem docile`.

module Docile
  extend ::Docile::Execution

  private

  def dsl_eval(dsl, *args, **_arg2_arg2, &block); end
  def dsl_eval_immutable(dsl, *args, **_arg2_arg2, &block); end
  def dsl_eval_with_block_return(dsl, *args, **_arg2_arg2, &block); end

  class << self
    def dsl_eval(dsl, *args, **_arg2_arg2, &block); end
    def dsl_eval_immutable(dsl, *args, **_arg2_arg2, &block); end
    def dsl_eval_with_block_return(dsl, *args, **_arg2_arg2, &block); end
  end
end

module Docile::BacktraceFilter
  def backtrace; end
  def backtrace_locations; end
end

Docile::BacktraceFilter::FILTER_PATTERN = T.let(T.unsafe(nil), Regexp)

class Docile::ChainingFallbackContextProxy < ::Docile::FallbackContextProxy
  def method_missing(method, *args, **_arg2_arg2, &block); end
end

module Docile::Execution
  private

  def exec_in_proxy_context(dsl, proxy_type, *args, **_arg3_arg3, &block); end

  class << self
    def exec_in_proxy_context(dsl, proxy_type, *args, **_arg3_arg3, &block); end
  end
end

class Docile::FallbackContextProxy
  def initialize(receiver, fallback); end

  def instance_variables; end
  def method_missing(method, *args, **_arg2_arg2, &block); end
end

Docile::FallbackContextProxy::NON_FALLBACK_METHODS = T.let(T.unsafe(nil), Set)
Docile::FallbackContextProxy::NON_PROXIED_INSTANCE_VARIABLES = T.let(T.unsafe(nil), Set)
Docile::FallbackContextProxy::NON_PROXIED_METHODS = T.let(T.unsafe(nil), Set)
Docile::VERSION = T.let(T.unsafe(nil), String)
