inherit_from:
  - http://shopify.github.io/ruby-style-guide/rubocop.yml

AllCops:
  Exclude:
    - vendor/**/*
  TargetRubyVersion: 2.5

Style/FrozenStringLiteralComment:
  Enabled: false

# This doesn't understand that <<~ doesn't exist in 2.0
Layout/HeredocIndentation:
  Enabled: false

# This doesn't take into account retrying from an exception
Lint/SuppressedException:
  Enabled: false

# allow String.new to create mutable strings
Style/EmptyLiteral:
  Enabled: false

# allow the use of globals which makes sense in a CLI app like this
Style/GlobalVars:
  Enabled: false

# allow using %r{} for regexes
Style/RegexpLiteral:
  Enabled: false

# allow readable Dev::Util.begin formatting
Style/MultilineBlockChain:
  Enabled: false
