inherit_gem:
  rubocop-shopify: rubocop-cli.yml

inherit_from:
  - .rubocop.sorbet.yml

plugins: rubocop-sorbet

AllCops:
  Exclude:
    - vendor/**/*
  NewCops: disable

Style/FrozenStringLiteralComment:
  Enabled: false

# This doesn't understand that <<~ doesn't exist in 2.0
Layout/HeredocIndentation:
  Enabled: false

# This doesn't take into account retrying from an exception
Lint/SuppressedException:
  Enabled: false

# allow String.new to create mutable strings
Style/EmptyLiteral:
  Enabled: false

# allow the use of globals which makes sense in a CLI app like this
Style/GlobalVars:
  Enabled: false

# allow using %r{} for regexes
Style/RegexpLiteral:
  Enabled: false

# allow readable Dev::Util.begin formatting
Style/MultilineBlockChain:
  Enabled: false

# we prefer rescue to align with the beginning of the line containing begin, not begin itself
Layout/RescueEnsureAlignment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

# We heavily manage output on purpose
Style/GlobalStdStream:
  Enabled: false
