up:
  - ruby: 2.3.3
  - bundler

commands:
  test:
    run: |
      if [ "$#" -eq 1 ] && [[ -f $1 ]];
      then
        rake test TEST=$1
      else
        rake test $@
      fi
  console: bin/console
  style: "bundle exec rubocop -D"
