up:
  - homebrew:
    - fswatch
  - ruby: 3.1.2
  - bundler

commands:
  test:
    run: |
      if [ "$#" -eq 1 ] && [[ -f $1 ]];
      then
        rake test TEST=$1
      else
        rake test $@
      fi
  style: "bundle exec rubocop -D"
  typecheck:
    run: srb
    aliases: [tc]
  watch:
    aliases: [w]
    subcommands:
      style:
        run: fswatch -e coverage -e "/\." -o . | xargs -n1 -I@ rake style
        aliases: [st]
      test:
        run: fswatch -e coverage -e "/\." -o . | xargs -n1 -I@ rake test
        alises: [t]
      typecheck:
        run: fswatch -e coverage -e "/\." -o . | xargs -n1 -I@ srb
        aliases: [tc]
      check:
        run: fswatch -e coverage -e "/\." -o . | xargs -n1 -I@ bash -c 'srb && rake style test'
        aliases: [ck]
