# typed: true
# frozen_string_literal: true

require 'bundler/setup'
require 'byebug'
require 'cli/ui'
require 'fileutils'
require 'io/console'
require 'minitest/autorun'
require 'mocha/minitest'
require 'open3'
require 'rbconfig'
require 'readline'
require 'rubygems'
require 'securerandom'
require 'stringio'
require 'strscan'
require 'tempfile'
require 'thread'
require 'timeout'
require 'tmpdir'
