# typed: true
# frozen_string_literal: true

require "bundler/setup"
require "byebug"
require "cli/ui"
require "cli/ui/frame"
require "cli/ui/frame/frame_stack"
require "cli/ui/frame/frame_style"
require "cli/ui/frame/frame_style/box"
require "cli/ui/frame/frame_style/bracket"
require "cli/ui/prompt/options_handler"
require "cli/ui/stdout_router"
require "fileutils"
require "io/console"
require "minitest/autorun"
require "mocha/minitest"
require "open3"
require "rbconfig"
require "readline"
require "rubygems"
require "securerandom"
require "stringio"
require "strscan"
require "tempfile"
require "thread"
require "timeout"
require "tmpdir"
