# typed: true
# frozen_string_literal: true

require 'digest'
require 'fileutils'
require 'net/http'
require 'uri'

module UnicodeWidthDataGenerator
  VERSION = '17.0.0'
  OUTPUT = File.expand_path('../lib/cli/ui/ansi/width_data.rb', __dir__)
  SOURCES = {
    'EastAsianWidth.txt' => {
      url: "https://www.unicode.org/Public/#{VERSION}/ucd/EastAsianWidth.txt",
      sha256: 'ea7ce50f3444a050333448dffef1cadd9325af55cbb764b4a2280faf52170a33',
    },
    'emoji-data.txt' => {
      url: "https://www.unicode.org/Public/#{VERSION}/ucd/emoji/emoji-data.txt",
      sha256: '2cb2bb9455cda83e8481541ecf5b6dfda66a3bb89efa3fa7c5297eccf607b72b',
    },
  }.freeze

  extend self

  #: -> void
  def generate
    sources = SOURCES.to_h do |name, source|
      data = fetch(source.fetch(:url))
      digest = Digest::SHA256.hexdigest(data)
      unless digest == source.fetch(:sha256)
        raise "#{name} SHA-256 mismatch: expected #{source.fetch(:sha256)}, got #{digest}"
      end

      [name, data]
    end

    ranges =
      property_ranges(sources.fetch('EastAsianWidth.txt')) { |property| property == 'W' || property == 'F' } +
      property_ranges(sources.fetch('emoji-data.txt')) { |property| property == 'Emoji_Presentation' }

    FileUtils.mkdir_p(File.dirname(OUTPUT))
    File.write(OUTPUT, render(merge(ranges)))
  end

  #: (String url) -> String
  def fetch(url)
    uri = URI(url)
    response = Net::HTTP.get_response(uri)
    raise "Failed to fetch #{url}: HTTP #{response.code}" unless response.is_a?(Net::HTTPSuccess)

    response.body
  end

  #: (String data) { (String property) -> bool } -> Array[Range[Integer]]
  def property_ranges(data)
    data.each_line.filter_map do |line|
      fields = line.split('#', 2).first.to_s.split(';', 2).map(&:strip)
      next if fields.length < 2 || !yield(fields.fetch(1))

      first, last = fields.fetch(0).split('..', 2)
      Range.new(Integer(first, 16), Integer(last || first, 16))
    end
  end

  #: (Array[Range[Integer]] ranges) -> Array[Range[Integer]]
  def merge(ranges)
    ranges.sort_by(&:begin).each_with_object([]) do |range, merged|
      previous = merged.last
      if previous && range.begin <= previous.end + 1
        merged[-1] = Range.new(previous.begin, [previous.end, range.end].max)
      else
        merged << range
      end
    end
  end

  #: (Array[Range[Integer]] ranges) -> String
  def render(ranges)
    source_comments = SOURCES.map do |name, source|
      "# - #{source.fetch(:url)}\n#   SHA-256: #{source.fetch(:sha256)} (#{name})"
    end.join("\n")
    ranges_sha256 = Digest::SHA256.hexdigest(serialize(ranges))
    entries = ranges.map do |range|
      "          #{format_codepoint(range.begin)}..#{format_codepoint(range.end)},"
    end.join("\n")

    <<~RUBY
      # typed: true
      # frozen_string_literal: true

      # Generated by `bundle exec rake unicode:generate_width_data`.
      # Unicode version: #{VERSION}
      # Unicode data © 2025 Unicode, Inc.
      # Terms: https://www.unicode.org/terms_of_use.html
      # Sources:
      #{source_comments}
      # Width ranges SHA-256: #{ranges_sha256}
      #
      # Do not edit this file by hand. Update the pinned version and checksums
      # in rakelib/unicode.rake, then regenerate it.

      module CLI
        module UI
          module ANSI
            module TerminalWidth
              UNICODE_VERSION = '#{VERSION}'

              # Codepoints with East_Asian_Width=Wide or Fullwidth, plus those
              # with Emoji_Presentation=Yes. VS16 presentation is handled by
              # TerminalWidth.grapheme_width because it is a property of the
              # cluster.
              WIDE_RANGES = [
      #{entries}
              ].freeze
            end
          end
        end
      end
    RUBY
  end

  #: (Array[Range[Integer]] ranges) -> String
  def serialize(ranges)
    ranges.map do |range|
      "#{format_codepoint(range.begin)}..#{format_codepoint(range.end)}"
    end.join("\n")
  end

  #: (Integer codepoint) -> String
  def format_codepoint(codepoint)
    format('0x%04X', codepoint)
  end
end

namespace :unicode do
  desc 'Regenerate terminal-width ranges from pinned Unicode data'
  task :generate_width_data do
    UnicodeWidthDataGenerator.generate
  end
end
